baseURL = 'https://antrontech.com/'
locale = 'en-us'
title = 'Antron Tech'
theme = 'tailbliss'
DefaultContentLanguage = 'en'
enableRobotsTXT = true
enableEmoji = true
enableInlineShortcodes = true
disableKinds = ['taxonomy', 'term']
ignoreFiles = ['content/posts/.*', 'content/prose.md']

[params]
  author = 'Antron Tech'
  description = 'Antron Tech develops reliable technology for defense and security applications in demanding operational environments.'
  moto = 'Reliable systems for demanding operational environments.'
  disable_theme_toggle = false
  disable_stay_uptodate = true

[menus]
  [[menus.main]]
    name = 'About'
    pageRef = '/about'
    weight = 10
  [[menus.main]]
    name = 'Capabilities'
    pageRef = '/capabilities'
    weight = 20
  [[menus.main]]
    name = 'Contact'
    pageRef = '/contact'
    weight = 30

  [[menus.footer]]
    name = 'About'
    pageRef = '/about'
    weight = 10
  [[menus.footer]]
    name = 'Capabilities'
    pageRef = '/capabilities'
    weight = 20
  [[menus.footer]]
    name = 'Contact'
    pageRef = '/contact'
    weight = 30

[taxonomies]
  category = 'Categories'
  tag = 'Tags'

[module]
  [module.hugoVersion]
    extended = true
    min = '0.148.2'
